#!/bin/sh
set -e

case "$2" in
up)
	/sbin/ifdown $1 # damn workaround.
	/sbin/ifup $1
	;;
down)
	# damn workaround again
	if [ "$1" = "wlan0" ]; then
		echo "skipping"
	else
		/sbin/ifdown $1
	fi
	;;
esac
