#!/bin/bash
#
# TC Control for UmbrellaNetwork
#

ETH0_MAX="80mbit"
ETH1_MAX="20mbit"
WLAN0_MAX="40mbit"

tc qdisc del dev wlan0 root 2>/dev/null
tc qdisc del dev eth0 root 2>/dev/null
tc qdisc del dev eth1 root 2>/dev/null

tc qdisc add dev eth1 root sfq perturb 10
tc qdisc add dev eth0 root sfq perturb 10
tc qdisc add dev wlan0 root sfq perturb 10

